#!/usr/bin/env python3
# pylint: disable=invalid-name
"""Validate and apply service-gate configs from /etc/wb-homeui/gates.d."""

import sys

from wb.homeui_backend.gates_cli import main

if __name__ == "__main__":
    sys.exit(main())
