"""Service gates: nginx port-gates rendered from gates.d/*.json declarations.

Declarations come from two dirs: package-installed ones in /usr/share and
admin-owned ones in /etc (an /etc gate overrides a package gate with the same
name). Rendered by the backend on startup and on every HTTPS toggle change, and
by the wb-homeui-gates CLI on demand, so gates always follow homeui's HTTP/HTTPS
mode.
"""

import fcntl
import json
import logging
import os
import re
import shutil
import subprocess  # nosec B404 - needed to run nginx -t / reload
import tempfile
import time
from dataclasses import dataclass, field
from typing import Optional

from .users_storage import UserType

GATES_CONF_DIR = "/etc/wb-homeui/gates.d"
PACKAGE_GATES_CONF_DIR = "/usr/share/wb-mqtt-homeui/gates.d"
GATES_CONF_DIRS = (PACKAGE_GATES_CONF_DIR, GATES_CONF_DIR)
RENDERED_GATES_DIR = "/var/lib/wb-homeui/nginx-gates"
BOUNCES_CONF_PATH = "/var/lib/wb-homeui/nginx/wb-gate-bounces.conf"
CUSTOM_MENU_DIR = "/var/lib/wb-homeui/custom-menu"
LOCK_PATH = "/run/wb-homeui-gates.lock"
# Parent of the auth-cache path from default.conf; nginx creates the leaf.
NGINX_CACHE_ROOT = "/var/cache/nginx"

GATE_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
RESERVED_PORTS = frozenset({80, 443})

GATE_TEMPLATE = """# Generated by wb-homeui-backend from {source}. DO NOT EDIT.
server {{
    listen {external_port}{ssl_suffix};
    server_name _;
    limit_req zone=wb_gate_perip burst=200 nodelay;
    limit_req_status 429;
{tls_include}    location / {{
{auth_location}        proxy_pass http://127.0.0.1:{internal_port};
        include /usr/share/wb-mqtt-homeui/nginx/snippets/wb-gate-proxy.inc;
    }}
{auth_server}{extra_include}}}
"""

AUTH_LOCATION_TEMPLATE = """        set $wb_role   {role};
        set $wb_return /open-{name};
        auth_request /wb_auth_check;
        error_page 401 = @wb_unauth;
"""

AUTH_SERVER_INCLUDES = """    include /usr/share/wb-mqtt-homeui/nginx/snippets/wb-gate-authcheck.inc;
    include /usr/share/wb-mqtt-homeui/nginx/snippets/wb-gate-unauth.inc;
"""

BOUNCE_TEMPLATE = "location = /open-{name} {{ return 302 {scheme}://$host:{external_port}/; }}\n"


@dataclass
class Gate:
    name: str
    internal_port: int
    external_port: int
    role: UserType
    auth: bool = True
    menu: Optional[dict] = None
    conf_dir: str = GATES_CONF_DIR


@dataclass
class ApplyResult:
    ok: bool
    gates: list[Gate] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    error: Optional[str] = None


def _parse_gate(name: str, config: dict, conf_dir: str = GATES_CONF_DIR) -> Gate:
    if not GATE_NAME_RE.match(name):
        raise ValueError(f"invalid gate name {name!r}")
    for key in ("internalPort", "externalPort"):
        if key not in config:
            raise ValueError(f"{key} is required")
    internal_port = config["internalPort"]
    external_port = config["externalPort"]
    for port in (internal_port, external_port):
        if not isinstance(port, int) or not 1024 <= port <= 65535 or port in RESERVED_PORTS:
            raise ValueError(f"invalid port {port!r}")
    if external_port == internal_port:
        raise ValueError("externalPort must differ from internalPort")
    auth = config.get("auth", True)
    if not isinstance(auth, bool):
        raise ValueError("invalid auth field")
    menu = config.get("menu")
    if menu is not None and (not isinstance(menu, dict) or not isinstance(menu.get("title"), dict)):
        raise ValueError("invalid menu field")
    return Gate(
        name=name,
        external_port=external_port,
        internal_port=internal_port,
        role=UserType(config.get("role", UserType.ADMIN.value)),
        auth=auth,
        menu=menu,
        conf_dir=conf_dir,
    )


def load_gates() -> tuple[list[Gate], list[str]]:
    gates_by_name: dict[str, Gate] = {}
    skipped: list[str] = []
    for conf_dir in GATES_CONF_DIRS:
        try:
            file_names = sorted(os.listdir(conf_dir))
        except FileNotFoundError:
            continue
        for file_name in file_names:
            if not file_name.endswith(".json"):
                continue
            path = os.path.join(conf_dir, file_name)
            try:
                with open(path, "r", encoding="utf-8") as f:
                    gate = _parse_gate(file_name[: -len(".json")], json.load(f), conf_dir)
                gates_by_name[gate.name] = gate
            except Exception as e:  # pylint: disable=broad-exception-caught
                skipped.append(f"{path}: {e}")
    return _check_port_conflicts(list(gates_by_name.values()), skipped)


def _check_port_conflicts(gates: list[Gate], skipped: list[str]) -> tuple[list[Gate], list[str]]:
    ready: list[Gate] = []
    # nginx listens on *:external, so an external equal to any internal clashes with the service.
    taken = {gate.internal_port for gate in gates}
    for gate in gates:
        if gate.external_port in taken:
            skipped.append(f"{gate.name}: externalPort {gate.external_port} is already used by another gate")
            continue
        taken.add(gate.external_port)
        ready.append(gate)
    return ready, skipped


def render_gate(gate: Gate, https_enabled: bool) -> str:
    """Render one gate server block; <name>.nginx.inc next to the JSON is included
    at server level as an escape hatch (broken ones are caught by nginx -t + rollback)."""
    extra_path = os.path.join(gate.conf_dir, gate.name + ".nginx.inc")
    return GATE_TEMPLATE.format(
        source=os.path.join(gate.conf_dir, gate.name + ".json"),
        external_port=gate.external_port,
        internal_port=gate.internal_port,
        ssl_suffix=" ssl" if https_enabled else "",
        tls_include=(
            "    include /usr/share/wb-mqtt-homeui/nginx/snippets/wb-gate-tls.inc;\n" if https_enabled else ""
        ),
        auth_location=(
            AUTH_LOCATION_TEMPLATE.format(role=gate.role.value, name=gate.name) if gate.auth else ""
        ),
        auth_server=AUTH_SERVER_INCLUDES if gate.auth else "",
        extra_include=f"    include {extra_path};\n" if os.path.exists(extra_path) else "",
    )


def _render_menu_item(gate: Gate) -> str:
    return json.dumps(
        {
            "id": "integrations",
            "children": [
                {
                    "id": gate.name,
                    "url": f"/open-{gate.name}",
                    "isExternal": True,
                    "openInNewTab": True,
                    **({"requiredRole": gate.role.value} if gate.auth else {}),
                    "title": gate.menu["title"],
                }
            ],
        },
        ensure_ascii=False,
        indent=2,
    )


def _write_rendered_files(gates: list[Gate], https_enabled: bool) -> None:
    os.makedirs(os.path.dirname(BOUNCES_CONF_PATH), exist_ok=True)
    scheme = "https" if https_enabled else "http"

    shutil.rmtree(RENDERED_GATES_DIR, ignore_errors=True)
    os.makedirs(RENDERED_GATES_DIR, exist_ok=True)
    bounces = []
    for gate in gates:
        with open(os.path.join(RENDERED_GATES_DIR, gate.name + ".conf"), "w", encoding="utf-8") as f:
            f.write(render_gate(gate, https_enabled))
        bounces.append(
            BOUNCE_TEMPLATE.format(name=gate.name, scheme=scheme, external_port=gate.external_port)
        )
    with open(BOUNCES_CONF_PATH, "w", encoding="utf-8") as f:
        f.writelines(bounces)


def _write_menu_items(gates: list[Gate]) -> None:
    os.makedirs(CUSTOM_MENU_DIR, exist_ok=True)
    prefix = "wb-gate-"
    for file_name in os.listdir(CUSTOM_MENU_DIR):
        if file_name.startswith(prefix):
            os.remove(os.path.join(CUSTOM_MENU_DIR, file_name))
    for gate in gates:
        if not gate.menu:
            continue
        path = os.path.join(CUSTOM_MENU_DIR, f"{prefix}{gate.name}.json")
        with open(path, "w", encoding="utf-8") as f:
            f.write(_render_menu_item(gate) + "\n")


def _snapshot_rendered_state(snapshot_dir: str) -> None:
    os.makedirs(RENDERED_GATES_DIR, exist_ok=True)
    shutil.copytree(RENDERED_GATES_DIR, os.path.join(snapshot_dir, "gates"))
    if os.path.exists(BOUNCES_CONF_PATH):
        shutil.copy(BOUNCES_CONF_PATH, os.path.join(snapshot_dir, "bounces.conf"))


def _restore_rendered_state(snapshot_dir: str) -> None:
    shutil.rmtree(RENDERED_GATES_DIR, ignore_errors=True)
    shutil.copytree(os.path.join(snapshot_dir, "gates"), RENDERED_GATES_DIR)
    snapshot_bounces = os.path.join(snapshot_dir, "bounces.conf")
    if os.path.exists(snapshot_bounces):
        shutil.copy(snapshot_bounces, BOUNCES_CONF_PATH)
    elif os.path.exists(BOUNCES_CONF_PATH):
        os.remove(BOUNCES_CONF_PATH)


NGINX_TEST_ATTEMPTS = 5
NGINX_TEST_RETRY_DELAY_S = 2


def _nginx_test() -> tuple[bool, str]:
    """nginx -t with retries: ATECC-backed keys in unrelated configs fail it
    transiently while another process (e.g. wb-cloud-agent) holds the chip."""
    for attempt in range(NGINX_TEST_ATTEMPTS):
        result = subprocess.run(  # nosec B603 - fixed constant argv
            ["/usr/sbin/nginx", "-t"], capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            return True, ""
        if attempt < NGINX_TEST_ATTEMPTS - 1:
            time.sleep(NGINX_TEST_RETRY_DELAY_S)
    return False, result.stderr.strip()


def _reload_nginx() -> None:
    subprocess.run(["/usr/bin/systemctl", "reload", "nginx"], check=True)  # nosec B603 - fixed constant argv


def _reload_nginx_best_effort() -> None:
    """Rollback-path reload: the config was just running, a failure can only be logged."""
    try:
        _reload_nginx()
    except subprocess.CalledProcessError as e:
        logging.error("Reload of the restored gate config also failed: %s", e)


def apply_gates(https_enabled: bool) -> ApplyResult:
    """Render all registered gates for the given mode and reload nginx.

    If nginx -t rejects the result, the previous rendered state is restored, so
    an unappliable gate can never break nginx or the already-working gates.
    """
    try:
        with open(LOCK_PATH, "w", encoding="utf-8") as lock_file:
            fcntl.flock(lock_file, fcntl.LOCK_EX)
            return _apply_gates_locked(https_enabled)
    except Exception as e:  # pylint: disable=broad-exception-caught
        logging.error("Failed to apply gates: %s", e)
        return ApplyResult(ok=False, error=str(e))


def _apply_gates_locked(https_enabled: bool) -> ApplyResult:
    os.makedirs(NGINX_CACHE_ROOT, exist_ok=True)
    gates, skipped = load_gates()
    for reason in skipped:
        logging.error("Skipping gate config %s", reason)
    with tempfile.TemporaryDirectory() as snapshot_dir:
        _snapshot_rendered_state(snapshot_dir)
        _write_rendered_files(gates, https_enabled)
        config_ok, nginx_error = _nginx_test()
        if not config_ok:
            _restore_rendered_state(snapshot_dir)
            logging.error("nginx -t rejected the rendered gates, previous state restored")
            return ApplyResult(ok=False, gates=gates, skipped=skipped, error=nginx_error)
        try:
            _reload_nginx()
        except subprocess.CalledProcessError as e:
            # Roll back so the rendered state matches what nginx is actually running.
            _restore_rendered_state(snapshot_dir)
            _reload_nginx_best_effort()
            logging.error("nginx reload failed, previous rendered state restored: %s", e)
            return ApplyResult(ok=False, gates=gates, skipped=skipped, error=str(e))
    # Menu only after a successful reload, best-effort: gates are live, a menu hiccup is no failure.
    try:
        _write_menu_items(gates)
    except OSError as e:
        logging.error("Failed to write gate menu items: %s", e)
    logging.info("Applied %d gate(s), https=%s", len(gates), https_enabled)
    return ApplyResult(ok=True, gates=gates, skipped=skipped)
