"""Service gates: nginx port-gates rendered from /etc/wb-homeui/gates.d/*.json.

Rendered by the backend on startup and on every HTTPS toggle change, and by the
wb-homeui-gates CLI on demand, so gates always follow homeui's HTTP/HTTPS mode.
"""

import fcntl
import json
import logging
import os
import re
import shutil
import subprocess  # nosec B404 - needed to run nginx -t / reload
import tempfile
import time
from dataclasses import dataclass, field
from typing import Optional

from .users_storage import UserType

GATES_CONF_DIR = "/etc/wb-homeui/gates.d"
RENDERED_GATES_DIR = "/var/lib/wb-homeui/nginx-gates"
BOUNCES_CONF_PATH = "/var/lib/wb-homeui/nginx/wb-gate-bounces.conf"
CUSTOM_MENU_DIR = "/usr/share/wb-mqtt-homeui/custom-menu"
LOCK_PATH = "/run/wb-homeui-gates.lock"
# Parent of the auth-cache path from wb-homeui-gates.conf; nginx creates the leaf.
NGINX_CACHE_ROOT = "/var/cache/nginx"

GATE_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
RESERVED_PORTS = frozenset({80, 443})
# Auto-assigned external ports live in 20000..39999: far from typical service
# neighbourhoods and recognizable as "a gate" in ss -ltn.
GATE_PORT_BLOCK_BASE = 20000
GATE_PORT_BLOCK_SIZE = 20000

GATE_TEMPLATE = """# Generated by wb-homeui-backend from {source}. DO NOT EDIT.
server {{
    listen {external_port}{ssl_suffix};
    server_name _;
{tls_include}    location / {{
{auth_location}        proxy_pass http://127.0.0.1:{internal_port};
        include /etc/nginx/snippets/wb-gate-proxy.inc;
    }}
{auth_server}{extra_include}}}
"""

AUTH_LOCATION_TEMPLATE = """        set $wb_role   {role};
        set $wb_return /open-{name};
        auth_request /wb_auth_check;
        error_page 401 = @wb_unauth;
"""

AUTH_SERVER_INCLUDES = """    include /etc/nginx/snippets/wb-gate-authcheck.inc;
    include /etc/nginx/snippets/wb-gate-unauth.inc;
"""

BOUNCE_TEMPLATE = "location = /open-{name} {{ return 302 {scheme}://$host:{external_port}/; }}\n"


@dataclass
class Gate:
    name: str
    internal_port: int
    role: UserType
    external_port: Optional[int] = None  # None until assigned by _assign_external_ports
    auth: bool = True
    title: Optional[dict] = None


@dataclass
class ApplyResult:
    ok: bool
    gates: list[Gate] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)  # "<file>: <reason>"
    error: Optional[str] = None


def _parse_gate(name: str, config: dict) -> Gate:
    if not GATE_NAME_RE.match(name):
        raise ValueError(f"invalid gate name {name!r}")
    internal_port = config["internalPort"]
    external_port = config.get("externalPort")
    ports = (internal_port,) if external_port is None else (internal_port, external_port)
    for port in ports:
        if not isinstance(port, int) or not 1024 <= port <= 65535 or port in RESERVED_PORTS:
            raise ValueError(f"invalid port {port!r}")
    if external_port == internal_port:
        raise ValueError("externalPort must differ from internalPort")
    auth = config.get("auth", True)
    if not isinstance(auth, bool):
        raise ValueError("invalid auth field")
    title = config.get("title")
    if title is not None and not isinstance(title, dict):
        raise ValueError("invalid title field")
    return Gate(
        name=name,
        external_port=external_port,
        internal_port=internal_port,
        role=UserType(config.get("role", UserType.ADMIN.value)),
        auth=auth,
        title=title,
    )


def load_gates() -> tuple[list[Gate], list[str]]:
    gates: list[Gate] = []
    skipped: list[str] = []
    try:
        file_names = sorted(os.listdir(GATES_CONF_DIR))
    except FileNotFoundError:
        return gates, skipped
    for file_name in file_names:
        if not file_name.endswith(".json"):
            continue
        path = os.path.join(GATES_CONF_DIR, file_name)
        try:
            with open(path, "r", encoding="utf-8") as f:
                gates.append(_parse_gate(file_name[: -len(".json")], json.load(f)))
        except Exception as e:  # pylint: disable=broad-exception-caught
            skipped.append(f"{path}: {e}")
    return _assign_external_ports(gates, skipped)


def _default_external_port(internal_port: int, taken: set[int]) -> int:
    # 20000 + internal % 20000: for a 4-digit internal this is literally "2"
    # prepended (9000 -> 29000). On a clash, deterministically probe onwards.
    for step in range(GATE_PORT_BLOCK_SIZE):
        candidate = GATE_PORT_BLOCK_BASE + (internal_port + step) % GATE_PORT_BLOCK_SIZE
        if candidate != internal_port and candidate not in taken:
            return candidate
    raise ValueError("no free port in the gate block")


def _assign_external_ports(gates: list[Gate], skipped: list[str]) -> tuple[list[Gate], list[str]]:
    ready: list[Gate] = []
    taken = {gate.internal_port for gate in gates}
    # Explicit ports are claimed first and never move; conflicts skip the gate.
    for gate in gates:
        if gate.external_port is None:
            continue
        if gate.external_port in taken:
            skipped.append(f"{gate.name}: externalPort {gate.external_port} is already used by another gate")
            continue
        taken.add(gate.external_port)
        ready.append(gate)
    for gate in gates:
        if gate.external_port is not None:
            continue
        gate.external_port = _default_external_port(gate.internal_port, taken)
        taken.add(gate.external_port)
        ready.append(gate)
    ready.sort(key=lambda gate: gate.name)
    return ready, skipped


def render_gate(gate: Gate, https_enabled: bool) -> str:
    # Escape hatch: <name>.nginx.inc next to the JSON is included at server level
    # (custom locations, timeouts). A broken one is caught by nginx -t + rollback.
    extra_path = os.path.join(GATES_CONF_DIR, gate.name + ".nginx.inc")
    return GATE_TEMPLATE.format(
        source=os.path.join(GATES_CONF_DIR, gate.name + ".json"),
        external_port=gate.external_port,
        internal_port=gate.internal_port,
        ssl_suffix=" ssl" if https_enabled else "",
        tls_include="    include /etc/nginx/snippets/wb-gate-tls.inc;\n" if https_enabled else "",
        auth_location=(
            AUTH_LOCATION_TEMPLATE.format(role=gate.role.value, name=gate.name) if gate.auth else ""
        ),
        auth_server=AUTH_SERVER_INCLUDES if gate.auth else "",
        extra_include=f"    include {extra_path};\n" if os.path.exists(extra_path) else "",
    )


def _render_menu_item(gate: Gate) -> str:
    return json.dumps(
        {
            "id": "integrations",
            "children": [
                {
                    "id": gate.name,
                    "url": f"/open-{gate.name}",
                    "isExternal": True,
                    "openInNewTab": True,
                    **({"requiredRole": gate.role.value} if gate.auth else {}),
                    "title": gate.title,
                }
            ],
        },
        ensure_ascii=False,
        indent=2,
    )


def _write_rendered_files(gates: list[Gate], https_enabled: bool) -> None:
    os.makedirs(RENDERED_GATES_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(BOUNCES_CONF_PATH), exist_ok=True)
    scheme = "https" if https_enabled else "http"

    for file_name in os.listdir(RENDERED_GATES_DIR):
        os.remove(os.path.join(RENDERED_GATES_DIR, file_name))
    bounces = []
    for gate in gates:
        with open(os.path.join(RENDERED_GATES_DIR, gate.name + ".conf"), "w", encoding="utf-8") as f:
            f.write(render_gate(gate, https_enabled))
        bounces.append(
            BOUNCE_TEMPLATE.format(name=gate.name, scheme=scheme, external_port=gate.external_port)
        )
    with open(BOUNCES_CONF_PATH, "w", encoding="utf-8") as f:
        f.writelines(bounces)


def _write_menu_items(gates: list[Gate]) -> None:
    os.makedirs(CUSTOM_MENU_DIR, exist_ok=True)
    prefix = "wb-gate-"
    for file_name in os.listdir(CUSTOM_MENU_DIR):
        if file_name.startswith(prefix):
            os.remove(os.path.join(CUSTOM_MENU_DIR, file_name))
    for gate in gates:
        if not gate.title:
            continue
        path = os.path.join(CUSTOM_MENU_DIR, f"{prefix}{gate.name}.json")
        with open(path, "w", encoding="utf-8") as f:
            f.write(_render_menu_item(gate) + "\n")


def _snapshot_rendered_state(snapshot_dir: str) -> None:
    os.makedirs(RENDERED_GATES_DIR, exist_ok=True)
    shutil.copytree(RENDERED_GATES_DIR, os.path.join(snapshot_dir, "gates"))
    if os.path.exists(BOUNCES_CONF_PATH):
        shutil.copy(BOUNCES_CONF_PATH, os.path.join(snapshot_dir, "bounces.conf"))


def _restore_rendered_state(snapshot_dir: str) -> None:
    shutil.rmtree(RENDERED_GATES_DIR, ignore_errors=True)
    shutil.copytree(os.path.join(snapshot_dir, "gates"), RENDERED_GATES_DIR)
    snapshot_bounces = os.path.join(snapshot_dir, "bounces.conf")
    if os.path.exists(snapshot_bounces):
        shutil.copy(snapshot_bounces, BOUNCES_CONF_PATH)


NGINX_TEST_ATTEMPTS = 5
NGINX_TEST_RETRY_DELAY_S = 2


def _nginx_test() -> tuple[bool, str]:
    # Retried: unrelated configs with ATECC-engine keys make nginx -t fail
    # transiently while another process (e.g. wb-cloud-agent) holds the chip.
    for attempt in range(NGINX_TEST_ATTEMPTS):
        result = subprocess.run(  # nosec B603 - fixed constant argv
            ["/usr/sbin/nginx", "-t"], capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            return True, ""
        if attempt < NGINX_TEST_ATTEMPTS - 1:
            time.sleep(NGINX_TEST_RETRY_DELAY_S)
    return False, result.stderr.strip()


def _reload_nginx() -> None:
    subprocess.run(["/usr/bin/systemctl", "reload", "nginx"], check=True)  # nosec B603 - fixed constant argv


def apply_gates(https_enabled: bool) -> ApplyResult:
    """Render all registered gates for the given mode and reload nginx.

    If nginx -t rejects the result, the previous rendered state is restored, so
    an unappliable gate can never break nginx or the already-working gates.
    """
    try:
        with open(LOCK_PATH, "w", encoding="utf-8") as lock_file:
            fcntl.flock(lock_file, fcntl.LOCK_EX)
            return _apply_gates_locked(https_enabled)
    except Exception as e:  # pylint: disable=broad-exception-caught
        logging.error("Failed to apply gates: %s", e)
        return ApplyResult(ok=False, error=str(e))


def _apply_gates_locked(https_enabled: bool) -> ApplyResult:
    os.makedirs(NGINX_CACHE_ROOT, exist_ok=True)
    gates, skipped = load_gates()
    for reason in skipped:
        logging.error("Skipping gate config %s", reason)
    with tempfile.TemporaryDirectory() as snapshot_dir:
        _snapshot_rendered_state(snapshot_dir)
        _write_rendered_files(gates, https_enabled)
        config_ok, nginx_error = _nginx_test()
        if not config_ok:
            _restore_rendered_state(snapshot_dir)
            logging.error("nginx -t rejected the rendered gates, previous state restored")
            return ApplyResult(ok=False, gates=gates, skipped=skipped, error=nginx_error)
    _write_menu_items(gates)
    _reload_nginx()
    logging.info("Applied %d gate(s), https=%s", len(gates), https_enabled)
    return ApplyResult(ok=True, gates=gates, skipped=skipped)
