// GENERATED from wb-rules.d.ts — do not edit by hand.
// Regenerate with: npm run generate:completions
import { snippetCompletion, type Completion } from '@codemirror/autocomplete';

export const wbRulesGlobals: Completion[] = [
  snippetCompletion('defineVirtualDevice(${1:name}, ${2:spec})', { label: 'defineVirtualDevice', type: 'function', detail: 'function defineVirtualDevice<S extends VirtualDeviceSpec>...' }),
  snippetCompletion('getDevice(${1:id})', { label: 'getDevice', type: 'function', detail: 'function getDevice(id: string): VirtualDevice | undefined;' }),
  snippetCompletion('getControl(${1:ref})', { label: 'getControl', type: 'function', detail: 'function getControl<K extends keyof WbControls & string>(...' }),
  snippetCompletion('cron(${1:spec})', { label: 'cron', type: 'function', detail: 'function cron(spec: string): CronEntry;' }),
  snippetCompletion('defineRule(${1:name}, ${2:spec})', { label: 'defineRule', type: 'function', detail: 'function defineRule(name: string, spec: RuleSpec): RuleId;' }),
  snippetCompletion('defineAlias(${1:aliasName}, ${2:cellRef})', { label: 'defineAlias', type: 'function', detail: 'function defineAlias(aliasName: string, cellRef: string):...' }),
  snippetCompletion('enableRule(${1:ruleId})', { label: 'enableRule', type: 'function', detail: 'function enableRule(ruleId: RuleId): void;' }),
  snippetCompletion('disableRule(${1:ruleId})', { label: 'disableRule', type: 'function', detail: 'function disableRule(ruleId: RuleId): void;' }),
  snippetCompletion('runRule(${1:ruleId})', { label: 'runRule', type: 'function', detail: 'function runRule(ruleId: RuleId): void;' }),
  { label: 'runRules', type: 'function', detail: 'function runRules(): void;', apply: 'runRules()' },
  { label: 'dev', type: 'variable', detail: '{ [K in keyof WbControls | (string & {})]: K extends keyo...' },
  { label: 'log', type: 'variable', detail: 'LogFunction' },
  snippetCompletion('debug(${1:format})', { label: 'debug', type: 'function', detail: 'function debug(format: string, ...args: any[]): void;' }),
  snippetCompletion('format(${1:format})', { label: 'format', type: 'function', detail: 'function format(format: string, ...args: any[]): string;' }),
  snippetCompletion('publish(${1:topic}, ${2:payload})', { label: 'publish', type: 'function', detail: 'function publish(topic: string, payload: CellValue, qos?:...' }),
  snippetCompletion('trackMqtt(${1:topic}, ${2:callback})', { label: 'trackMqtt', type: 'function', detail: 'function trackMqtt(topic: string, callback: (message: Mqt...' }),
  snippetCompletion('nextMqtt(${1:topic})', { label: 'nextMqtt', type: 'function', detail: 'function nextMqtt(topic: string, timeoutMs?: number): Pro...' }),
  { label: 'timers', type: 'variable', detail: 'Record<string, Timer>' },
  snippetCompletion('startTimer(${1:name}, ${2:milliseconds})', { label: 'startTimer', type: 'function', detail: 'function startTimer(name: string, milliseconds: number): ...' }),
  snippetCompletion('startTicker(${1:name}, ${2:milliseconds})', { label: 'startTicker', type: 'function', detail: 'function startTicker(name: string, milliseconds: number):...' }),
  snippetCompletion('changed(${1:ctrl})', { label: 'changed', type: 'function', detail: 'function changed<K extends keyof WbControls & string>(ctr...' }),
  snippetCompletion('sleep(${1:milliseconds})', { label: 'sleep', type: 'function', detail: 'function sleep(milliseconds: number): Promise<void>;' }),
  snippetCompletion('setTimeout(${1:callback}, ${2:milliseconds})', { label: 'setTimeout', type: 'function', detail: 'function setTimeout(callback: () => void, milliseconds: n...' }),
  snippetCompletion('setInterval(${1:callback}, ${2:milliseconds})', { label: 'setInterval', type: 'function', detail: 'function setInterval(callback: () => void, milliseconds: ...' }),
  snippetCompletion('clearTimeout(${1:id})', { label: 'clearTimeout', type: 'function', detail: 'function clearTimeout(id: number): void;' }),
  snippetCompletion('clearInterval(${1:id})', { label: 'clearInterval', type: 'function', detail: 'function clearInterval(id: number): void;' }),
  snippetCompletion('runShellCommand(${1:command})', { label: 'runShellCommand', type: 'function', detail: 'function runShellCommand(command: string, options?: Shell...' }),
  snippetCompletion('spawn(${1:command})', { label: 'spawn', type: 'function', detail: 'function spawn(command: string, args?: string[] | null, o...' }),
  snippetCompletion('readConfig(${1:path})', { label: 'readConfig', type: 'function', detail: 'function readConfig(path: string, options?: ReadConfigOpt...' }),
  snippetCompletion('PersistentStorage(${1:name})', { label: 'PersistentStorage', type: 'function', detail: 'function PersistentStorage<T extends Record<string, any> ...' }),
  snippetCompletion('StorableObject(${1:obj})', { label: 'StorableObject', type: 'function', detail: 'function StorableObject<T extends object>(obj: T): T & Re...' }),
  { label: 'Notify', type: 'variable', detail: 'NotifyApi' },
  { label: 'Alarms', type: 'variable', detail: 'AlarmsApi' },
  { label: '__filename', type: 'variable', detail: 'string' },
  { label: 'module', type: 'variable', detail: '{ readonly filename: string; readonly static?: Record<str...' },
  snippetCompletion('require(${1:id})', { label: 'require', type: 'function', detail: 'function require(id: string): any;' }),
  { label: 'global', type: 'variable', detail: 'typeof globalThis' },
  { label: 'exports', type: 'variable', detail: 'Record<string, any>' },
];
